<?php

namespace AppBundle\Repository;

/**
 * HousingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HousingRepository extends \Doctrine\ORM\EntityRepository
{
}
